//
//  ASDataMacros.h
//  FootballStar
//
//  Created by CarlHwang on 13-9-27.
//  Copyright (c) 2013年 AfroStudio. All rights reserved.
//

#import "ASFunctionMacros.h"

///-------------------------- separate line -------------------------///

#pragma mark -
#pragma mark ASViewController - /*BaseController widgets' layout*/
#pragma mark NAVIGATIONBAR
#define NAVIGATION_BAR_ORIGIN (DEVICE_BASIC_IPHONE() ? NAVIGATION_BAR_IPHONE_ORIGIN : CGPointMake(0,0))
#define NAVIGATION_BAR_IPHONE_ORIGIN (DEVICE_SCREEN_4INCHES() ? CGPointMake(0,0) : CGPointMake(0,0))

#pragma mark BUTTON
#define BACK_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 40 : 96)
#define BACKCLICK_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 50 : 116)
#define BACK_BUTTON_CENTER (DEVICE_BASIC_IPHONE() ? BACK_BUTTON_IPHONE_CENTER : CGPointMake(70,50))
#define BACK_BUTTON_IPHONE_CENTER (DEVICE_SCREEN_4INCHES() ? CGPointMake(35,25) : CGPointMake(35,25))

//#pragma mark TIPS VIEW
//#define TIPS_VIEW_FRAME() (DEVICE_BASIC_IPHONE() ? CGRectMake(0, 0, 235, 143) : CGRectMake(0, 0, 550, 263))
//#define TIPS_TEXT_VIEW_FRAME() (DEVICE_BASIC_IPHONE() ? CGRectMake(35, 0, 150, 127) : CGRectMake(100, 0, 320, 241))
//#define TIPS_TEXT_VIEW_FRAME_1ST() (DEVICE_BASIC_IPHONE() ? CGRectMake(20, 0, 165, 127) : CGRectMake(70, 0, 340, 241))
#define TIPS_VIEW_FONTSIZE (DEVICE_BASIC_IPHONE() ? 18 : 36)

#pragma mark AFRO VIEW
#define AFRO_VIEW_FRAME() (DEVICE_BASIC_IPHONE() ? AFRO_VIEW_IPHONE_FRAME() : CGRectMake(280, 0, 228, 228))
#define AFRO_VIEW_IPHONE_FRAME() (DEVICE_SCREEN_4INCHES() ? CGRectMake(115, 0, 107, 107) : CGRectMake(115, 0, 107, 107))
#define AFRO_MISSION_VIEW_FRAME() (DEVICE_BASIC_IPHONE() ? CGRectMake(65, 60, 20, 20) : CGRectMake(135, 125, 45, 45))
#define AFRO_MISSION_FONTSIZE_2NUM (DEVICE_BASIC_IPHONE() ? 14 : 28)
#define AFRO_MISSION_FONTSIZE_3NUM (DEVICE_BASIC_IPHONE() ? 12 : 24)

///-------------------------- separate line -------------------------///

#pragma mark -
#pragma mark GameController - /*shake buttons' layout, pageView's frame, keyboard's layout*/
#define LIGHT_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 40 : 96)
#define LIGHTCLICK_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 50 : 116)
#define TRASH_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 40 : 96)
#define TRASHCLICK_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 50 : 116)
#define SHARE_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 40 : 96)
#define SHARECLICK_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 50 : 116)
#define COIN_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 40 : 96)
#define COINCLICK_BUTTON_LENGTH (DEVICE_BASIC_IPHONE() ? 50 : 116)

#define LIGHT_BUTTON_CENTER (DEVICE_BASIC_IPHONE() ? LIGHT_BUTTON_IPHONE_CENTER : CGPointMake(160,250))
#define LIGHT_BUTTON_IPHONE_CENTER (DEVICE_SCREEN_4INCHES() ? CGPointMake(70,145) : CGPointMake(70,125))
#define SHARE_BUTTON_CENTER (DEVICE_BASIC_IPHONE() ? SHARE_BUTTON_IPHONE_CENTER : CGPointMake(384,250))
#define SHARE_BUTTON_IPHONE_CENTER (DEVICE_SCREEN_4INCHES() ? CGPointMake(160,145) : CGPointMake(160,125))
#define TRASH_BUTTON_CENTER (DEVICE_BASIC_IPHONE() ? TRASH_BUTTON_IPHONE_CENTER : CGPointMake(608,250))
#define TRASH_BUTTON_IPHONE_CENTER (DEVICE_SCREEN_4INCHES() ? CGPointMake(250,145) : CGPointMake(250,125))
#define COIN_BUTTON_CENTER (DEVICE_BASIC_IPHONE() ? CGPointMake(20,20) : CGPointMake(48,48))

#define REWARD_LABEL_ORIGIN_Y (DEVICE_BASIC_IPHONE() ? REWARD_LABEL_IPHONE_ORIGIN_Y : 585)
#define REWARD_LABEL_IPHONE_ORIGIN_Y (DEVICE_SCREEN_4INCHES() ? 345 : 285)

#pragma mark TIPS VIEW
#define TIPS_VIEW_FRAME() (DEVICE_BASIC_IPHONE() ? TIPS_VIEW_IPHONE_FRAME() : CGRectMake(0, 305, 768,270))
#define TIPS_VIEW_IPHONE_FRAME() (DEVICE_SCREEN_4INCHES() ? CGRectMake(0, 195, 320, 140) : CGRectMake(0, 150, 320, 140))

#define MAIN_KEYBOARD_START_XCOORD 0
#define MAIN_KEYBOARD_START_YCOORD (DEVICE_BASIC_IPHONE() ? DEVICE_SCREEN_HEIGHT()-120 : DEVICE_SCREEN_HEIGHT()-288)
#define MAIN_KEYBOARD_SIDE_LENGTH (DEVICE_BASIC_IPHONE() ? 40 : 96)

#define ANSWER_KEYBOARD_START_YCOORD (DEVICE_BASIC_IPHONE() ? ANSWER_KEYBOARD_IPHONE_START_YCOORD : DEVICE_SCREEN_HEIGHT()-400)
#define ANSWER_KEYBOARD_IPHONE_START_YCOORD (DEVICE_SCREEN_4INCHES() ? DEVICE_SCREEN_HEIGHT()-190 : DEVICE_SCREEN_HEIGHT()-170)

///-------------------------- separate line -------------------------///

#pragma mark - 
#pragma mark LevelController - /*layout*/
#define LEVEL_PAGE_CASE_X_NUM (DEVICE_BASIC_IPHONE() ? LEVEL_PAGE_CASE_IPHONE_WIDTH : 4)
#define LEVEL_PAGE_CASE_IPHONE_WIDTH (DEVICE_SCREEN_4INCHES() ? 4 : 4 )
#define LEVEL_PAGE_CASE_Y_NUM (DEVICE_BASIC_IPHONE() ? LEVEL_PAGE_CASE_IPHONE_HEIGHT : 4)
#define LEVEL_PAGE_CASE_IPHONE_HEIGHT (DEVICE_SCREEN_4INCHES() ? 5 : 4 )

#define CASE_WIDTH (DEVICE_BASIC_IPHONE() ? 56 : 131)
#define CASECLICK_BUTTON_WIDTH (DEVICE_BASIC_IPHONE() ? 56 : 131)
#define CASE_HEIGHT (DEVICE_BASIC_IPHONE() ? 52 : 121)
#define CASECLICK_BUTTON_HEIGHT (DEVICE_BASIC_IPHONE() ? 52 : 121)

#define LEVEL_PAGE_CASE_INSET_X (DEVICE_BASIC_IPHONE() ? 20 : 50)
#define LEVEL_PAGE_CASE_INSET_Y (DEVICE_BASIC_IPHONE() ? 20 : 50)

#define CASE_MISSION_VIEW_FRAME() (DEVICE_BASIC_IPHONE() ? CGRectMake(18, 33, 20, 20) : CGRectMake(42, 75, 45, 45))


